name: Project test & build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install 🔧
        run: |
          if [ -d 'project' ]; then cd project && npm install; else echo 'Skip. The project directory does not exist'; fi

      - name: Run Test 🔨
        run: |
          if [ -d 'project' ]; then cd project && npm test; else echo 'Skip. The project directory does not exist'; fi

      - name: Build 👷
        run: |
          if [ -d 'project' ]; then cd project && npm run build; else echo 'Skip. The project directory does not exist'; fi

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.ST_LUCKKY }}
          BRANCH: gh-pages
          FOLDER: project/build
          CLEAN: true
